name: Community Action

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
#     build:
#         runs-on: ubuntu-latest
#         steps:
#             - uses: actions/checkout@v2
#             - name: Checkout code
#               run: echo "Checkout Code"
#               shell: bash

#     get-github-context:
#         runs-on: ubuntu-latest
#         steps:
#             - name: "Get GitHub context"
#               run: echo '${{ toJson(github.event) }}' | jq
#               shell: bash

    community-action:
        runs-on: ubuntu-latest
        steps:
            - name: Create Comment"
              uses: peter-evans/create-or-update-comment@v2
              with:
                  comment-id: ${{ github.event.comment.id }}
                  body: "Hello from the community action :sparkles:"
                  reactions: "+1"




