name: My First GitHub Action

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Checkout code
              run: echo "Checkout Code"
              shell: bash

    get-github-context:
        runs-on: ubuntu-latest
        steps:
            - name: "Get GitHub context"
              run: echo '${{ toJson(github.event) }}' | jq
              shell: bash



